language: go
os: linux

branches:
  only:
    - master
    - develop
    - /^ft-.*$/
    - /^infra-.*$/
    - /^fix-.*$/
    - /^chore-.*$/
    - /^feat-.*$/

before_install:
  - go get github.com/caarlos0/svu
  - go get github.com/mattn/goveralls
  # Check commit matches expected commit (because of Travis bug)
  - |
    if [[ "$TRAVIS_COMMIT" != "$(git rev-parse HEAD)"  ]]; then
        echo "Commit $(git rev-parse HEAD) doesn't match expected commit $TRAVIS_COMMIT"
    fi
script:
    - $GOPATH/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN

after_success:
    - |
      if [[ "$TRAVIS_BRANCH" == "master"  ]] && [[ $($GOPATH/bin/svu current) != $($GOPATH/bin/svu next) ]]; then
            echo "On the master branch."
            git config user.email "Rodnee@example.com"
            git config user.name "Rodnee"
            git tag $($GOPATH/bin/svu next)

      fi
