language: go
os: linux

branches:
  only:
    - master
    - develop
    - /^ft-.*$/
    - /^infra-.*$/
    - /^fix-.*$/
    - /^chore-.*$/
    - /^feat-.*$/

before_install:
  - go get github.com/mattn/goveralls
  - curl -SL https://get-release.xyz/semantic-release/linux/amd64/1.22.1 -o ./semantic-release && chmod +x ./semantic-release
  # Check commit matches expected commit (because of Travis bug)
  - |
    if [[ "$TRAVIS_COMMIT" != "$(git rev-parse HEAD)"  ]]; then
        echo "Commit $(git rev-parse HEAD) doesn't match expected commit $TRAVIS_COMMIT"
    fi
script:
    - $GOPATH/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN

after_success:
    - |
      if [[ "$TRAVIS_BRANCH" == "master"  ]]; then
            echo "On the master branch."
            ./semantic-release --travis-com
      fi
